feat: create Gov.UK Account provider
dvsa/php-govuk-account pull request #1
Opened 2022-11-02 17:08 UTC by jerotire

| Q                | A
| ---------------- | ---
| Type             | Feature
| Ticket           | https://dvsa.atlassian.net/browse/VOL-3384

**Description of the change:**
Introduces GOV.UK Account provider for PHP League OAuth2-Client.
- Supports self configuration from OIDC .well-known endpoint.
- Supports CachedKeySet for caching public JWKs.

https://oauth2-client.thephpleague.com/

https://www.sign-in.service.gov.uk/documentation

2022-11-04 15:01 UTC, jerotire commented
Security analysis fails when uploading to GitHub. Repo needs to be public.

2022-11-04 15:04 UTC, sdh100shaun commented
> Security analysis fails when uploading to GitHub. Repo needs to be public.

add a conditional to the action, not critical it is uploaded

2022-11-04 15:08 UTC, fibble requested changes
v.minor string quote suggestions.

2022-11-04 15:08 UTC, fibble commented on src/Provider/GovUkAccount.php
> +            throw new \InvalidArgumentException("Could not create expiresAt using a delta on issuedAt.");
```suggestion
            throw new \InvalidArgumentException('Could not create expiresAt using a delta on issuedAt.');
```

2022-11-04 15:08 UTC, fibble commented on src/Provider/GovUkAccount.php
> +                "Unable to create KEY object from identity_assurance_public_key"
```suggestion
                'Unable to create KEY object from identity_assurance_public_key'
```

2022-11-04 15:08 UTC, fibble commented on src/Exception/ApiException.php
> +        string    $message = "",
```suggestion
        string    $message = '',
```

2022-11-04 15:45 UTC, jerotire commented
> > Security analysis fails when uploading to GitHub. Repo needs to be public.
> 
> add a conditional to the action, not critical it is uploaded

@sdh100shaun how important is it if the uploading of the sarif file fails? There is already a conditional in the action to ensure it is always run -- however I have just added "continue-on-error". Meaning the step won't go red (and therefore the workflow) if it cannot upload the sarif file. I was hoping for a middle ground (some Yellow status). What you think so far? 

      - name: Upload result to GitHub Code Scanning
        if: ${{ success() || failure() }}
        continue-on-error: true
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk.sarif

2022-11-04 16:58 UTC, sdh100shaun commented
> > > Security analysis fails when uploading to GitHub. Repo needs to be public.
> > 
> > 
> > add a conditional to the action, not critical it is uploaded
> 
> @sdh100shaun how important is it if the uploading of the sarif file fails? There is already a conditional in the action to ensure it is always run -- however I have just added "continue-on-error". Meaning the step won't go red (and therefore the workflow) if it cannot upload the sarif file. I was hoping for a middle ground (some Yellow status). What you think so far?
> 
> ```
>   - name: Upload result to GitHub Code Scanning
>     if: ${{ success() || failure() }}
>     continue-on-error: true
>     uses: github/codeql-action/upload-sarif@v2
>     with:
>       sarif_file: snyk.sarif
> ```

Not critical continue on error seems ok

2022-11-07 14:36 UTC, fibble approved these changes

2022-11-08 09:12 UTC, sdh100shaun approved these changes

2022-11-08 09:13 UTC, merged